# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dateBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod "FSCalendar"
    pod 'RealmSwift'


  target 'dateBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dateBookUITests' do
    # Pods for testing
  end

end
